# Generated by Django 5.0.3 on 2024-03-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('current_location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('experience_status', models.CharField(choices=[('F', 'Fresher'), ('E', 'Experienced')], max_length=1)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_summary', models.TextField()),
                ('key_skills', models.CharField(max_length=255)),
                ('projects', models.TextField()),
                ('education', models.TextField()),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('certification_details', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('languages_known', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
