# Generated by Django 5.0.3 on 2024-03-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
